### ISSUE TITLE
Consider removing jQuery dependency

### ISSUE THREAD

**Issue by cvan** [youmustfight/aframe-asset-lazy-load#1]
First off, really great work here! I especially like the chunking. So glad you wrote this. :+1: 

I checked the [source](https://github.com/youmustfight/aframe-asset-lazy-load/blob/master/index.js), and I didn't see any specific reason why jQuery would be needed. The `$` calls could be replaced with `document.querySelector` (and `document.querySelectorAll` where appropriate) and `$(el).attr(…)` calls would just become `el.getAttribute(…)` calls.

FWIW, we have [some utils for querying elements](https://github.com/aframevr/aframe/blob/e495525/src/elements/lib/utils.js#L7-L61) à la jQuery's `$`:
- `$` which returns a single element
- `$$` which returns an array (instead of a `NodeList`)

In `0.1.0`/`master` of `aframe`/`aframe-core`, we aren't exposing these `utils`. But when we release `0.2.0`, you'll be able to do `require('aframe').utils.$` (or `window.AFRAME.utils.$`).

**Comment by youmustfight** [comment]
Totally agree, next thing I'm going to do. I was stuck on the load event for the asset.

**Comment by youmustfight** [comment]
jQuery annihilated!
